// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ncwW2Qgif2pGwQDF81hXqa
// Component: e6HpMvhYjvtJ
import * as React from "react";
import { useRouter } from "next/router";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  hasVariant,
  useCurrentUser,
  usePlasmicTranslator
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import ResultBox from "../../ResultBox"; // plasmic-import: EmHW-l0fTCHr/component
import { useScreenVariants as useScreenVariants_2BvNreuf1Eto } from "./PlasmicGlobalVariant__DesktopBase"; // plasmic-import: 2BVNreuf1ETO/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: ncwW2Qgif2pGwQDF81hXqa/projectcss
import sty from "./PlasmicRecentRecords.module.css"; // plasmic-import: e6HpMvhYjvtJ/css

createPlasmicElementProxy;

export const PlasmicRecentRecords__VariantProps = new Array();

export const PlasmicRecentRecords__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicRecentRecords__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  console.log(props,"PlasmicRecentRecords__RenderFunc")
  const $translator = usePlasmicTranslator?.();
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  const globalVariants = ensureGlobalVariants({
    desktopBase: useScreenVariants_2BvNreuf1Eto()
  });
  let gameList = overrides.resultArea.props;
  console.log(gameList,"gameList")
  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"resultArea"}
      data-plasmic-override={overrides.resultArea}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.resultArea
      )}
    >
      <ResultBox
        className={classNames("__wab_instance", sty.resultBox___4E76P)}
        lose={
          hasVariant(globalVariants, "desktopBase", "desktopOnly")
            ? ["airdrop"]
            : ["vehicle"]
        }
        win={
          hasVariant(globalVariants, "desktopBase", "desktopOnly")
            ? []
            : undefined
        }
      />

      <ResultBox
        className={classNames("__wab_instance", sty.resultBox__cofFq)}
        lose={
          hasVariant(globalVariants, "desktopBase", "desktopOnly")
            ? []
            : undefined
        }
        win={
          hasVariant(globalVariants, "desktopBase", "desktopOnly")
            ? ["firstAid"]
            : ["airdrop"]
        }
      />

      <ResultBox
        className={classNames("__wab_instance", sty.resultBox__xZ2Du)}
        lose={
          hasVariant(globalVariants, "desktopBase", "desktopOnly")
            ? ["vehicle"]
            : ["firstAid"]
        }
        win={
          hasVariant(globalVariants, "desktopBase", "desktopOnly")
            ? []
            : undefined
        }
      />
    </Stack__>
  );
}

const PlasmicDescendants = {
  resultArea: ["resultArea"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicRecentRecords__ArgProps,
          internalVariantPropNames: PlasmicRecentRecords__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicRecentRecords__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "resultArea") {
    func.displayName = "PlasmicRecentRecords";
  } else {
    func.displayName = `PlasmicRecentRecords.${nodeName}`;
  }
  return func;
}

export const PlasmicRecentRecords = Object.assign(
  // Top-level PlasmicRecentRecords renders the root element
  makeNodeComponent("resultArea"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicRecentRecords
    internalVariantProps: PlasmicRecentRecords__VariantProps,
    internalArgProps: PlasmicRecentRecords__ArgProps
  }
);

export default PlasmicRecentRecords;
/* prettier-ignore-end */
