// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ncwW2Qgif2pGwQDF81hXqa
// Component: I0ZtuiJGttrZ
import * as React from "react";
import { useRouter } from "next/router";
import {
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useCurrentUser,
  usePlasmicTranslator
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import CurrencyBar from "../../CurrencyBar"; // plasmic-import: hl5_weK0MHHX/component
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: ncwW2Qgif2pGwQDF81hXqa/projectcss
import sty from "./PlasmicCurrencySelection.module.css"; // plasmic-import: I0ZtuiJGttrZ/css

createPlasmicElementProxy;

export const PlasmicCurrencySelection__VariantProps = new Array();

export const PlasmicCurrencySelection__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCurrencySelection__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $translator = usePlasmicTranslator?.();
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"_2\u9009\u62e9\u8d27\u5e01"}
        data-plasmic-override={overrides._2选择货币}
        className={classNames(projectcss.all, sty._2选择货币)}
      >
        <div
          data-plasmic-name={"text"}
          data-plasmic-override={overrides.text}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text
          )}
        >
          <Trans__>{"2. \u9009\u62e9\u8d27\u5e01"}</Trans__>
        </div>
      </div>
      <CurrencyBar
        bar={["bar1"]}
        className={classNames("__wab_instance", sty.currencyBar__ey8Hj)}
      />

      <CurrencyBar
        bar={["bar2"]}
        className={classNames("__wab_instance", sty.currencyBar__k06J9)}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "_2\u9009\u62e9\u8d27\u5e01", "text"],
  _2选择货币: ["_2\u9009\u62e9\u8d27\u5e01", "text"],
  text: ["text"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCurrencySelection__ArgProps,
          internalVariantPropNames: PlasmicCurrencySelection__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCurrencySelection__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCurrencySelection";
  } else {
    func.displayName = `PlasmicCurrencySelection.${nodeName}`;
  }
  return func;
}

export const PlasmicCurrencySelection = Object.assign(
  // Top-level PlasmicCurrencySelection renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    _2选择货币: makeNodeComponent("_2\u9009\u62e9\u8d27\u5e01"),
    text: makeNodeComponent("text"),
    // Metadata about props expected for PlasmicCurrencySelection
    internalVariantProps: PlasmicCurrencySelection__VariantProps,
    internalArgProps: PlasmicCurrencySelection__ArgProps
  }
);

export default PlasmicCurrencySelection;
/* prettier-ignore-end */
