// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ncwW2Qgif2pGwQDF81hXqa
// Component: EmHW-l0fTCHr
import * as React from "react";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  hasVariant,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: ncwW2Qgif2pGwQDF81hXqa/projectcss
import sty from "./PlasmicResultBox.module.css"; // plasmic-import: EmHW-l0fTCHr/css

createPlasmicElementProxy;

export const PlasmicResultBox__VariantProps = new Array("win", "lose");

export const PlasmicResultBox__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicResultBox__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $translator = usePlasmicTranslator?.();
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "win",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.win
      },
      {
        path: "lose",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.lose
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  return (
    <div
      data-plasmic-name={"_1stGame"}
      data-plasmic-override={overrides._1stGame}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty._1stGame,
        { [sty._1stGamewin_airdrop]: hasVariant($state, "win", "airdrop") }
      )}
    >
      <div
        data-plasmic-name={"rectangle4234"}
        data-plasmic-override={overrides.rectangle4234}
        className={classNames(projectcss.all, sty.rectangle4234, {
          [sty.rectangle4234lose_airdrop]: hasVariant(
            $state,
            "lose",
            "airdrop"
          ),
          [sty.rectangle4234lose_firstAid]: hasVariant(
            $state,
            "lose",
            "firstAid"
          ),
          [sty.rectangle4234lose_vehicle]: hasVariant($state, "lose", "vehicle")
        })}
      >
        <div
          data-plasmic-name={
            "pngtreeHandPaintedCommercialGameEatChicken40297883"
          }
          data-plasmic-override={
            overrides.pngtreeHandPaintedCommercialGameEatChicken40297883
          }
          className={classNames(
            projectcss.all,
            sty.pngtreeHandPaintedCommercialGameEatChicken40297883,
            {
              [sty.pngtreeHandPaintedCommercialGameEatChicken40297883lose_airdrop]:
                hasVariant($state, "lose", "airdrop"),
              [sty.pngtreeHandPaintedCommercialGameEatChicken40297883lose_firstAid]:
                hasVariant($state, "lose", "firstAid"),
              [sty.pngtreeHandPaintedCommercialGameEatChicken40297883lose_vehicle]:
                hasVariant($state, "lose", "vehicle"),
              [sty.pngtreeHandPaintedCommercialGameEatChicken40297883win_airdrop]:
                hasVariant($state, "win", "airdrop"),
              [sty.pngtreeHandPaintedCommercialGameEatChicken40297883win_firstAid]:
                hasVariant($state, "win", "firstAid"),
              [sty.pngtreeHandPaintedCommercialGameEatChicken40297883win_vehicle]:
                hasVariant($state, "win", "vehicle")
            }
          )}
        />
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  _1stGame: [
    "_1stGame",
    "rectangle4234",
    "pngtreeHandPaintedCommercialGameEatChicken40297883"
  ],

  rectangle4234: [
    "rectangle4234",
    "pngtreeHandPaintedCommercialGameEatChicken40297883"
  ],

  pngtreeHandPaintedCommercialGameEatChicken40297883: [
    "pngtreeHandPaintedCommercialGameEatChicken40297883"
  ]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicResultBox__ArgProps,
          internalVariantPropNames: PlasmicResultBox__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicResultBox__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "_1stGame") {
    func.displayName = "PlasmicResultBox";
  } else {
    func.displayName = `PlasmicResultBox.${nodeName}`;
  }
  return func;
}

export const PlasmicResultBox = Object.assign(
  // Top-level PlasmicResultBox renders the root element
  makeNodeComponent("_1stGame"),
  {
    // Helper components rendering sub-elements
    rectangle4234: makeNodeComponent("rectangle4234"),
    pngtreeHandPaintedCommercialGameEatChicken40297883: makeNodeComponent(
      "pngtreeHandPaintedCommercialGameEatChicken40297883"
    ),
    // Metadata about props expected for PlasmicResultBox
    internalVariantProps: PlasmicResultBox__VariantProps,
    internalArgProps: PlasmicResultBox__ArgProps
  }
);

export default PlasmicResultBox;
/* prettier-ignore-end */
